### ISSUE TITLE
Implement better interactive containers

### ISSUE THREAD

**Issue by MickMake** [gearboxworks/gearbox#37]
Docker doesn't handle interactive containers too well.
The best solution to address this is to:
1. <s>Run an SSHD within each interactive container. </s> _(Now #39)_
2. <s>Interactive container created with specific hostname.</s> _(Now #41)_
3. <s>GoLang (host) queries VM docker for: (IP|HOSTNAME):PORT combo. Uses this to start interactive session.</s> _(Now #42)_
4. <s>Map VM directories into the container</s> _(Now #43)_

**Comment by mikeschinkel** [comment]
We broke this out into multiple other tickets.
