### ISSUE TITLE
Implement dynamic ports for SSHD

### ISSUE THREAD

**Issue by mikeschinkel** [gearboxworks/gearbox#42]
GoLang (host) queries VM docker for: (IP|HOSTNAME):PORT combo. Uses this to start interactive session.

**Everything should be done in Go,** not in bash.

See [github.com/moby/moby](https://github.com/moby/moby) as potential package.

We might need to go directly to the REST API: 
- https://docs.docker.com/engine/api/v1.40/

## In Bash
```
ssh -p $(docker port <container_name> | awk -F: '/^22\/tcp/{print$2}') gearbox@localhost <cli-app>
```
Example:
```
ssh -p $(docker port golang-1.13.1 | awk -F: '/^22\/tcp/{print$2}') gearbox@localhost go
```

**Comment by MickMake** [comment]
This has required several rebuilds of containers.

Essentially, my process has been:
1. Rebuild one container
2. Test.
3. Any bugs/changes/corrections found to the generic `docker-gearbox` container - recursively go back through previous containers and re-test.

Changes made are working on the assumption that everything is dynamic.
EG: `EXPOSE` ports are now to be exposed using the `-P` flag. This guarantees no port clashes, however, extra work is required to discover ports to be used within containers.

**Comment by MickMake** [comment]
Implemented within docker-template and docker-gearbox-base
