### ISSUE TITLE
Set up Docker build process using Actions

### ISSUE THREAD

**Issue by mikeschinkel** [gearboxworks/gearbox#48]
This includes consolidating duplicated logic into one place such as `Makefile`.

Also renaming [github.com/gearboxworks/docker-gearbox](https://github.com/gearboxworks/docker-gearbox) to [github.com/gearboxworks/docker-base](https://github.com/gearboxworks/docker-base) 

It *might* include moving to [Github Package repository](https://github.com/features/packages) from Docker Hub *if* it is a lot easier to build and deploy to Github.com via. DockerHub.com.

**Comment by MickMake** [comment]
New build process now incorporated into [docker-template](https://github.com/gearboxworks/docker-template)
