### ISSUE TITLE
Diagnose Docker pull issue that requires login when running on Linux host.

### ISSUE THREAD

**Issue by mikeschinkel** [gearboxworks/gearbox#50]
This is the problem that @pr0logas experienced where he gets a popup to login to Docker Hub when issuing a `git pull` command from within GearboxOS

**Comment by pr0logas** [comment]
I used gearboxworks - gearbox from github on 0.5.1 branch.
https://github.com/gearboxworks/gearbox/tree/0.5.1

And did this:
```
./gearbox box start
./gearbox ssh
docker pull gearbox/php
```
Result:
```
Using default tag: latest
Error response from daemon: pull access denied for gearbox/php, repository does not exist or may require 'docker login'
```

Maybe I did something wrong, maybe in wrong order? Or I only can do it with Gearbox CLI (with box)

**Comment by mikeschinkel** [comment]
@MickMake Can you help @pr0logas ?

**Comment by MickMake** [comment]
I believe this is caused by the ssh-agentd passing authentication on to the VM.
This has been disabled on the VM with `AllowAgentForwarding = False`
