### ISSUE TITLE
Add mysql.ini in MySQL/MariaDB containers

### ISSUE THREAD

**Issue by mikeschinkel** [gearboxworks/gearbox#56]
Add `mysql.ini` in MySQL/MariaDB containers.  This includes updating `max_allowed_packet` to `256M`. 

This includes https://github.com/wplib/wplib-box/issues/587

**Comment by MickMake** [comment]
Added `max_allowed_packet` to `build/rootfs/etc/mysql/my.cnf` to all MySQL & MariaDB containers.
