### ISSUE TITLE
Host Heartbeat and low level control

### ISSUE THREAD

**Issue by MickMake** [gearboxworks/gearbox#7]
[Branch](https://github.com/gearboxworks/gearbox/tree/7-Host-Heartbeat) to add code for:

- `gearbox heartbeat` - New sub-command to gearbox app running on host.
- Manages NFS exports changes.
- Ensures NFSD is running.
- Provides systray, (in compliance with Apple’s app policy).
- Add itself as a boot launcher in the O/S.
- Basic comms with the `VM Heartbeat`, (IE showing VM state & alerts in systray).

**Comment by mikeschinkel** [comment]
@MickMake Where are we on this? Can we close, or is there still more to do?
